### ISSUE TITLE
More alt mods

### ISSUE THREAD

**Issue by jasonm23** [jasonm23/ristretto-affogato-keycaps#12]
Added from #10
- [x] Adding a 1.75u "fn" (some poker 2 and 3 users go with the fn mapped to caps lock).
- [x] A short shift (1.75u - useful on compact 75% layouts like this http://ortholinearkeyboards.com/top-plates/neutrino-top-plate and this http://winkeyless.kr/product/b-mini-x2-pcb/)
- [x] Extra left shift (2.25u for fc660m users)

@rjmana

**Comment by jasonm23** [comment]
Will add to the planck etc. kit

**Comment by rjmana** [comment]
yeah, i was thinking that when this set releases that i'd just grab the planck kit to fill out other boards. the extra 2.25u will definitely be something fc660m users will want, and there are a number of those

**Comment by jasonm23** [comment]
I think _most_ people will have some understanding of how this all works.  It's not really possible to keep the costs down and at the same time offer complete kits for each variation.

**Comment by jasonm23** [comment]
That said, it's infuriating to see **ONE** key you need on a child kit that'll cost you $40 ... :(

**Comment by rjmana** [comment]
> That said, it's infuriating to see ONE key you need on a child kit that'll cost you $40 ... :(

i feel ya. that's the biggest challenge you face i guess - where to place these alternate keys. i think an alternate mod kit is best for that but then the planck kit covers a lot of the alt mods too. challenge now is to keep both sets reasonable, so that if needed, one can get both without breaking the bank. it's also a good thing you don't have too many novelties as that increases the overall price

**Comment by jasonm23** [comment]
Oh I just noticed, I will need the row numbers for these.

**Comment by jasonm23** [comment]
The small layouts kit (60% planck etc.) has the 1.75u shift. (I need it for a 78%)

**Comment by jasonm23** [comment]
Extra left shift? 2.25u ... Standard layout provides this.

**Comment by jasonm23** [comment]
I'll assume r3 for the 1.75u Fn

**Comment by rjmana** [comment]
re 1.75u shift: yes, just noticed it. so that's covered

extra left shift for fc660ms their layout is one that uses a 2.25 shift on both the left and the right to make space for the arrow cluster https://elitekeyboards.com/proddata/images/th/fc660m_full1000_th620x400.jpg

re 1.75u fn - yes, R3. to cut costs, i'm personally okay with blanks for that space or with using the caps lock on it, but i just like having the option. edit: tbh, you might not need to add it in. i'm personally okay with using the ^ key you have in the Alt Caps/Ctrl/Backspace

**Comment by jasonm23** [comment]
I've added it, I'll put the extra 2.25 shift somewhere!

**Comment by jasonm23** [comment]
Ok those are updated, I'll update the preview image in a moment

**Comment by rjmana** [comment]
lol @ all the requests bunched in together under "60%/Planck/JD40/78%/Filco Minila kit"

**Comment by jasonm23** [comment]
I know ... ! :-/

**Comment by jasonm23** [comment]
Ok closing this
